export const modules = {
  "Module 1: Onboarding": [
    "1-1 Initial document collation",
    "1-2 Client system onboarding",
    "1-2-1 Additional DOT onboarding",
    "1-3 Worker hire",
    "1-4 New customer addition",
    "1-5 Client process change",
    "1-6 Benefits onboarding",
  ],
  "Module 2: Active Worker Management": [
    "2-1 1st day check in & re-cap",
    "2-2 Timesheet collation",
    "2-2-1 Timesheet receipt",
    "2-2-2 Timesheet chase",
    "2-2-3 Timesheet Issue Resolution",
    "2-3 Urgent late timesheet escalation",
    "2-4 Employee Happiness call",
    "2-5 Employer/Employee discussion",
  ],
  "Module 3: Payroll Administration": [
    "3-1 Time Manual Entry",
    "3-2 Time Semi-Automated Entry",
    "3-3 Final Payroll Review",
    "3-4 Garnishment administration",
    "3-5 Sick & PTO administration",
    "3-6 Non regular Payroll run",
    "3-7 Benefit Deduction Management",
    "3-8 Benefit ACA Monthly reporting",
    "3-9 State Discussions",
  ],
  "Module 4: Customer Invoice Administration": [
    "4-1 Invoice creation",
    "4-2 Reconciliation report",
    "4-3 Enquiries & Corrections",
    "4-4 Accounts Payable Escalation",
  ],
  "Module 5: Offboarding": [
    "5-1 Planning",
    "5-2 Execution",
    "5-3 COBRA/Ex-employee tally report",
  ],
  "Module 6: HSE Incident & Claims Management": [
    "6-1 Incident Management",
    "6-2 Claim Management",
    "6-3 Custom HSE consulting",
    "6-4 HSE training portal subscription",
    "6-5 HSE training employee access",
  ],
  "Module 7: Workers Compensation Insurance Optimization": [
    "7-1 Job class code assessment",
    "7-2 Workers Compensation Audit Preparation",
  ],
};
